### ISSUE TITLE
Build trtorch failed in ubuntu

### ISSUE THREAD

**Issue by inocsin** [NVIDIA/TRTorch#229] opened 2020-11-18 12:23 UTC
I try to build the project with bazel but failed.

my environment:
gcc: 7.5.0
g++: 7.5.0
cuda: 10.2
cudnn: 7.6.5
tensorRT: 7.0.0.11

error log:
[log.txt](https://github.com/NVIDIA/TRTorch/files/5559949/log.txt)

$ bazel build //:libtrtorch --compilation_mode opt

Starting local Bazel server and connecting to it...
INFO: Analyzed target //:libtrtorch (39 packages loaded, 2546 targets configured).
INFO: Found 1 target...
ERROR: /home/vincent/Projects/TRTorch/cpp/trtorchc/BUILD:10:10: Linking of rule '//cpp/trtorchc:trtorchc' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-opt/bin/cpp/trtorchc/trtorchc-2.params

Use --sandbox_debug to see verbose messages from the sandbox
external/tensorrt/lib/x86_64-linux-gnu/libnvinfer_static.a(helpers.o):helpers.cpp:function nvinfer1::getNvrtcMajorVersion(): error: undefined reference to 'nvrtcVersion'
external/tensorrt/lib/x86_64-linux-gnu/libnvinfer_static.a(profile.o):profile.cpp:function nvtxDomainSyncUserReleasing_impl_init_v3: error: undefined reference to 'dlopen'
external/tensorrt/lib/x86_64-linux-gnu/libnvinfer_static.a(profile.o):profile.cpp:function nvtxDomainSyncUserReleasing_impl_init_v3: error: undefined reference to 'dlsym'
external/tensorrt/lib/x86_64-linux-gnu/libnvinfer_static.a(profile.o):profile.cpp:function nvtxDomainSyncUserReleasing_impl_init_v3: error: undefined reference to 'dlclose'
external/tensorrt/lib/x86_64-linux-gnu/libnvinfer_static.a(profile.o):profile.cpp:function nvtxDomainResourceDestroy_impl_init_v3: error: undefined reference to 'dlopen'
external/tensorrt/lib/x86_64-linux-gnu/libnvinfer_static.a(profile.o):profile.cpp:function nvtxDomainResourceDestroy_impl_init_v3: error: undefined reference to 'dlsym'
external/tensorrt/lib/x86_64-linux-gnu/libnvinfer_static.a(profile.o):profile.cpp:function nvtxDomainResourceDestroy_impl_init_v3: error: undefined reference to 'dlclose'
external/tensorrt/lib/x86_64-linux-gnu/libnvinfer_static.a(profile.o):profile.cpp:function nvtxDomainDestroy_impl_init_v3: error: undefined reference to 'dlopen'
external/tensorrt/lib/x86_64-linux-gnu/libnvinfer_static.a(profile.o):profile.cpp:function nvtxDomainDestroy_impl_init_v3: error: undefined reference to 'dlsym'
external/tensorrt/lib/x86_64-linux-gnu/libnvinfer_static.a(profile.o):profile.cpp:function nvtxDomainDestroy_impl_init_v3: error: undefined reference to 'dlclose'
external/tensorrt/lib/x86_64-linux-gnu/libnvinfer_static.a(profile.o):profile.cpp:function nvtxMarkA_impl_init_v3: error: undefined reference to 'dlopen'
external/tensorrt/lib/x86_64-linux-gnu/libnvinfer_static.a(profile.o):profile.cpp:function nvtxMarkA_impl_init_v3: error: undefined reference to 'dlsym'
external/tensorrt/lib/x86_64-linux-gnu/libnvinfer_static.a(profile.o):profile.cpp:function nvtxMarkA_impl_init_v3: error: undefined reference to 'dlclose'

could you help solve this problem, thanks a lot
@narendasan

**Comment by inocsin** [comment] 2020-11-19 04:41
> @inocsin: Can you try this workaround and let us know if it helps?
> https://github.com/NVIDIA/TRTorch/blob/3279274f8a29edc9235efaed3ddf2a154772c245/third_party/tensorrt/local/BUILD#L63-L81
It still doesn't work. Besides, I try to import libnvrtc_static.a in third_party/tensorrt/local/BUILD, still has the same linking problem.

`cc_import(
    name = "nvrtc",
    static_library = select({
        ":aarch64_linux": 
            "lib/x86_64-linux-gnu/stubs/libnvrtc_static.a",
        ":windows": 
            "lib/x64/nvrtc.lib",
        "//conditions:default": 
            "lib/x86_64-linux-gnu/stubs/libnvrtc_static.a",
    }),
    visibility = ["//visibility:private"],
)`

I give up building with local installed cudnn and tensorrt, and download given tarball in WORKSAPCE, install using following command. It finally worked.

`bazel build //:libtrtorch --compilation_mode opt --distdir third_party/dist_dir/[x86_64-linux-gnu | aarch64-linux-gnu]`

**Comment by narendasan** [comment] 2020-11-19 19:58
I think the issue here is that bazel is preferring static libraries and we have had trouble in the past with static linking. It should be fixed with #190. On x86 we recommend building from tarballs anyway since the builds will be fully reproducible then.

**Comment by inocsin** [comment] 2020-11-20 02:22
> I think the issue here is that bazel is preferring static libraries and we have had trouble in the past with static linking. It should be fixed with #190. On x86 we recommend building from tarballs anyway since the builds will be fully reproducible then.

Thanks, I have built trtorch with tarball successfully now.

**Closed** 2020-11-20 02:23 UTC
Labels: question
