### ISSUE TITLE
❓ [Question] We don't have an op for aten::addmm

### ISSUE THREAD

**Issue by lablabla** [NVIDIA/TRTorch#230] opened 2020-11-18 15:41 UTC
## ❓ Question

I'm trying to convert a modified version of Yolov3 to TesnorRT, I have the model scripted to TorchScript and I'm trying to run trtorchexec on it
I'm getting an error
```
Checking operator support
terminate called after throwing an instance of 'c10::Error'
  what():  0 INTERNAL ASSERT FAILED at "../torch/csrc/jit/ir/alias_analysis.cpp":461, please report a bug to PyTorch. We don't have an op for aten::addmm but it isn't a special case.  Argument types: Tensor, int[], int[], int[], int[], bool,
Exception raised from analyzeImpl at ../torch/csrc/jit/ir/alias_analysis.cpp:461 (most recent call first):
```

I'm using the `pytorch_update` branch (since I need to use pytorch 1.7.0 & cuda 11.1), and I've merge master into it to get the latest updates (https://github.com/lablabla/TRTorch/tree/pytorch_update)

## Environment

> Build information about the TRTorch compiler can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0): 1.7.0
 - CPU Architecture:
 - OS (e.g., Linux): Ubuntu 16.04
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): Built TRTorch from sources, Bazel downloads prebuilt 1.7.0
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives: local sources
 - Python version: 3.8.5
 - CUDA version: 11.1
 - GPU models and configuration: GeForce GTX 980
 - Any other relevant information:

## Additional context

I saw this commit https://github.com/NVIDIA/TRTorch/commit/c5b6202 so I figured `aten:addmm` should be supported, but I guess I'm missing something

**Comment by narendasan** [comment] 2020-11-19 20:06
This is an error from Libtorch not TRTorch since we use libtorch to pull out function schemas, which leads me to believe its a pytorch version mismatch. Was the model you are trying created with PyTorch 1.7.0 as well?

**Comment by peri044** [comment] 2020-11-21 23:02
@lablabla Can you share a minimal repro of your torchscript model for me to narrow down the root cause?

**Comment by lablabla** [comment] 2020-11-22 13:10
@narendasan I think you're right. I thought I generated it using the same PyTorch version, but I just generate the TorchScript file 
again and run trtorchexec again. This time I'm getting a different error (still getting the previous one with the old file):

```
Checking operator support
DEBUG: [TRTorch - Debug Build] - RemoveTo - Note: Removing remaining aten::to operators, if type casts need to be preserved, add a pass before this pass is run
terminate called after throwing an instance of 'torch::jit::ErrorReport'
  what():
temporary: the only valid use of a module is looking up an attribute but found  = prim::SetAttr[name="ny"](%67, %ny.2)
:
```

@peri044 , I scripted the original yolov3, and getting the same error, [this is the model](https://drive.google.com/file/d/1hgy5oH6qdS3G-2iDkGh-eKScSnA4D2G6/view?usp=sharing)

I'm running it like this:
```
bazelisk run //cpp/trtorchexec yolov3-608x608-cuda-fp32.pt 1x3x608x608
```

**Comment by peri044** [comment] 2020-11-23 01:20
The error is coming from [libtorch lowering call](https://github.com/NVIDIA/TRTorch/blob/master/core/lowering/lowering.cpp#L71). 
Looks like graph lowering doesn't support attribute setting as mentioned in [this issue](https://github.com/pytorch/pytorch/issues/43948#issuecomment-707891246). 
Can you try tracing the model and running it with TRTorch [as per this suggestion](https://github.com/pytorch/pytorch/issues/43948#issuecomment-685925788) to see if it works?

**Comment by lablabla** [comment] 2020-11-23 08:25
@peri044 
After tracing I'm getting
```
Checking operator support
terminate called after throwing an instance of 'trtorch::Error'
  what():  [enforce fail at core/conversion/conversion.cpp:392] Expected schema to be true but got false
Unable to get schema for Node %526 : Tensor = aten::reciprocal(%523) # /home/devel/anaconda3/envs/trtorch/lib/python3.8/site-packages/torch/tensor.py:521:0 (conversion.VerifyCoverterSupportForBlock)
```
Traced model can be found [here](https://drive.google.com/file/d/1vcSWFjDjeIxBlm7I8BxM2avkOeJqsx1g/view?usp=sharing)

**Comment by peri044** [comment] 2020-12-04 23:47
This error is due to `RemoveTo` lowering pass. The schema for aten::reciprocal consumes a tensor but post lowering, the input is an integer. 
Before lowering graph structure:
```
%6189 : Tensor = aten::to(%nx.1, %5940, %275, %275, %276)
%6190 : Tensor = aten::reciprocal(%6189)
```
After `passes::RemoveTo(g)` lowering [here](https://github.com/NVIDIA/TRTorch/blob/master/core/lowering/lowering.cpp#L48)
```
%5940 : int = prim::Constant[value=6]()
%5956 : Tensor = aten::reciprocal(%5940)
```
Looks like there is a bug in the lowering call. This can be investigated in a separate github issue. Can you try compiling without the `RemoveTo` lowering pass and proceed with network conversion ?

**Comment by lablabla** [comment] 2020-12-05 11:40
Compiling without the `RemoveTo`, you mean simply to comment out the line you linked to?

**Comment by peri044** [comment] 2020-12-06 19:37
Yes.

**Comment by peri044** [comment] 2020-12-06 20:13
Okay the issue is due incorrect node replacement after `aten::to` removal.
Please replace this line 
```
n->outputs()[0]->replaceAllUsesWith(n->inputs()[1]);
```
with 
```
n->outputs()[0]->replaceAllUsesWith(n->inputs()[0]);
```
Now the reciprocal graph after lowering seems to be correct after the fix 
```
%nx.2 : Tensor = prim::NumToTensor(%523)
%536 : Tensor = aten::reciprocal(%nx.2)
```
Please compile using this fix for now. There's a pending [PR](https://github.com/NVIDIA/TRTorch/pull/234) for this which will be integrated into master branch.

**Closed** 2021-04-20 00:02 UTC
Labels: No Activity, question
